version: "3"

services:
  sql_server:
    image: microsoft/mssql-server-linux
    ports:
      - "1433:1433"
    environment:
      - HOMEBREW_NO_ENV_FILTERING=1
      - ACCEPT_EULA=Y
      - SA_PASSWORD=

  etl_api:
    build: .
    ports:
      - "3000:3000"
    environment:
      - SOURCE_DB_HOST=sql_server
      - SOURCE_DB_PORT=1433
      - SOURCE_DB_USERNAME=sa
      - SOURCE_DB_PASSWORD=
      - DB_HOST=sql_server
      - DB_PORT=1433
      - DB_USERNAME=sa
      - DB_PASSWORD=
      - ROOT_PATH=/usr/app
    depends_on:
      - sql_server
